/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */
import type { AccountEventControllerGetAllType } from './accountEventControllerGetAllType'

export type AccountEventControllerGetAllParams = {
  /**
   * Account id of the AccountEvent
   */
  account_id?: string
  /**
   * Type of the AccountEvent
   */
  type?: AccountEventControllerGetAllType
  /**
   * Description of the AccountEvent
   */
  description?: string
  /**
   * Sort by AccountEvent created_at
   */
  sort_by_created_at?: string
  /**
   * Sort by AccountEvent updated_at
   */
  sort_by_updated_at?: string
  offset?: number
  page?: number
}
