/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordDTO {
  /** Id of the account */
  account_id: string
  /** Current password of the account */
  password: string
  /** New password of the account */
  new_password: string
  /** New password confirmation */
  new_password_confirmation: string
}
