/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional additional error details such as stack traces or debug information.
 */
export type ErrorResponseError = { [key: string]: unknown }
