/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponseError } from './errorResponseError'

export interface ErrorResponse {
  /** The HTTP status code representing the type of error. */
  status_code: number
  /** A human-readable message summarizing the error. */
  message: string
  /** The URL path where the error occurred. */
  path: string
  /** The timestamp of when the error was generated in ISO 8601 format. */
  timestamp: string
  /** Optional additional error details such as stack traces or debug information. */
  error?: ErrorResponseError
}
