/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */

export interface Pagination {
  /** Current page */
  page: number
  /** Total of items returned */
  total: number
  /** Items per page */
  pageSize: number
  /** Total pages count */
  pageCount: number
  /** Is there a previous page */
  hasPreviousPage: boolean
  /** Is there a next page */
  hasNextPage: boolean
}
