/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */

export interface ResetPasswordDTO {
  /** Id of the account */
  account_id: string
  /** New password of the account */
  password: string
  /** New password confirmation */
  password_confirmation: string
  /** Token received in the email */
  token: string
}
