/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */
import type { Pagination } from './pagination'

export interface ResponseMetaDTO {
  /** Pagination information */
  pagination: Pagination
}
