/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseAccountDTO } from './responseAccountDTO'
import type { ResponseMetaDTO } from './responseMetaDTO'

export interface ResponseAccountListDTO {
  /** List of Account */
  data: ResponseAccountDTO[]
  /** Meta information */
  meta: ResponseMetaDTO
}
