/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseAccountEventDTO } from './responseAccountEventDTO'
import type { ResponseMetaDTO } from './responseMetaDTO'

export interface ResponseAccountEventListDTO {
  /** List of AccountEvent */
  data: ResponseAccountEventDTO[]
  /** Meta information */
  meta: ResponseMetaDTO
}
