/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseAccountDTO } from './responseAccountDTO'
import type { ResponseBlogPostDTO } from './responseBlogPostDTO'

export interface ResponseCommentDTO {
  /** Post id of the Comment */
  post_id: number
  /** Content of the Comment */
  content: string
  /** Account id of the Comment */
  account_id: string
  /** Comment id */
  id: number
  /** Author of the Comment */
  account?: ResponseAccountDTO
  /** Post of the Comment */
  post?: ResponseBlogPostDTO
  /** Date of creation */
  created_at: string
  /** Date of last update */
  updated_at: string
  /** Date of deletion */
  deleted_at: string
}
