/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateBlogPostDTO {
  /** Title of the BlogPost */
  title?: string
  /** Content of the BlogPost */
  content?: string
  /** Author id of the BlogPost */
  author_id?: string
  /** Excerpt of the BlogPost */
  excerpt?: string
  /** Cover image of the BlogPost */
  cover_image?: string
  /** Published at of the BlogPost */
  published_at?: string
  /** Read time of the BlogPost */
  read_time?: number
}
