/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Rennan API
 * The Rennan API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateAccountDTO {
  /** Email of the Account */
  email?: string
  /** Password of the account */
  password?: string
  /** Is email verified of the Account */
  is_email_verified?: boolean
  /** Is active of the Account */
  is_active?: boolean
  /** Is admin of the Account */
  is_admin?: boolean
  /** Is moderator of the Account */
  is_moderator?: boolean
  /** Name of the Account */
  name?: string
  /** First name of the Account */
  first_name?: string
  /** Last name of the Account */
  last_name?: string
  /** Lead origin of the Account */
  lead_origin?: string
  /** Photo url of the Account */
  photo_url?: string
  /** Birth date of the Account */
  birth_date?: string
  /** Refresh token of the Account */
  refresh_token?: string
  /** Token version of the Account */
  token_version?: number
}
